In [1]:
import gc
import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

parquet_path = "/kaggle/input/datasets/tjaycuz/us-flight-data/US_flight_data.parquet"

pf = pq.ParquetFile(parquet_path)
print(f"Rows: {pf.metadata.num_rows:,} | Columns: {pf.metadata.num_columns}")

Rows: 32,957,871 | Columns: 119

In [2]:
md = pf.metadata
names = pf.schema_arrow.names
nulls = dict.fromkeys(names, 0)

for rg in range(md.num_row_groups):
    row_group = md.row_group(rg)
    for i, name in enumerate(names):
        stats = row_group.column(i).statistics
        if stats is not None and stats.has_null_count:
            nulls[name] += stats.null_count

null_df = (pd.DataFrame({"column": list(nulls), "nulls": list(nulls.values())})
             .assign(null_pct=lambda d: (d["nulls"] / md.num_rows * 100).round(2))
             .sort_values("null_pct", ascending=False)
             .reset_index(drop=True))
null_df.head(40)

                       column     nulls  null_pct
0   SCH_OP_CARRIER_AIRLINE_ID  32956489    100.00
1              SCH_OP_CARRIER  32956489    100.00
2       SCH_OP_CARRIER_FL_NUM  32956489    100.00
3       SCH_OP_UNIQUE_CARRIER  32956489    100.00
4          DIV3_LONGEST_GTIME  32957862    100.00
5             DIV3_WHEELS_OFF  32957866    100.00
6               DIV3_TAIL_NUM  32957866    100.00
7                DIV4_AIRPORT  32957871    100.00
8             DIV4_AIRPORT_ID  32957871    100.00
9         DIV4_AIRPORT_SEQ_ID  32957871    100.00
10             DIV4_WHEELS_ON  32957871    100.00
11           DIV4_TOTAL_GTIME  32957871    100.00
12         DIV4_LONGEST_GTIME  32957871    100.00
13            DIV4_WHEELS_OFF  32957871    100.00
14              DIV4_TAIL_NUM  32957871    100.00
15               DIV5_AIRPORT  32957871    100.00
16            DIV5_AIRPORT_ID  32957871    100.00
17        DIV5_AIRPORT_SEQ_ID  32957871    100.00
18             DIV5_WHEELS_ON  32957871    100.00
19           DIV5_TOTAL_GTIME  32957871    100.00
20         DIV5_LONGEST_GTIME  32957871    100.00
21            DIV5_WHEELS_OFF  32957871    100.00
22              DIV5_TAIL_NUM  32957871    100.00
23               DIV2_AIRPORT  32957019    100.00
24            DIV2_AIRPORT_ID  32957018    100.00
25        DIV2_AIRPORT_SEQ_ID  32957018    100.00
26             DIV2_WHEELS_ON  32957019    100.00
27           DIV2_TOTAL_GTIME  32957019    100.00
28         DIV2_LONGEST_GTIME  32957019    100.00
29            DIV2_WHEELS_OFF  32957467    100.00
30              DIV2_TAIL_NUM  32957467    100.00
31               DIV3_AIRPORT  32957862    100.00
32            DIV3_AIRPORT_ID  32957861    100.00
33        DIV3_AIRPORT_SEQ_ID  32957861    100.00
34             DIV3_WHEELS_ON  32957862    100.00
35           DIV3_TOTAL_GTIME  32957862    100.00
36              DIV1_TAIL_NUM  32879408     99.76
37    DIV_ACTUAL_ELAPSED_TIME  32880014     99.76
38              DIV_ARR_DELAY  32880013     99.76
39            DIV1_WHEELS_OFF  32879408     99.76

In [2]:
names = pf.schema_arrow.names
md = pf.metadata
nulls = dict.fromkeys(names, 0)
for rg in range(md.num_row_groups):
    r = md.row_group(rg)
    for i, n in enumerate(names):
        nulls[n] += r.column(i).statistics.null_count

total = md.num_rows
for i, n in enumerate(names):
    print(f"{i:3d}  {n:<28} {nulls[n]/total*100:6.2f}% null")

  0  YEAR                           0.00% null
  1  QUARTER                        0.00% null
  2  MONTH                          0.00% null
  3  DAY_OF_MONTH                   0.00% null
  4  DAY_OF_WEEK                    0.00% null
  5  FL_DATE                        0.00% null
  6  MKT_UNIQUE_CARRIER            64.06% null
  7  BRANDED_CODE_SHARE            64.06% null
  8  MKT_CARRIER_AIRLINE_ID        64.06% null
  9  MKT_CARRIER                   64.06% null
 10  MKT_CARRIER_FL_NUM            64.06% null
 11  SCH_OP_UNIQUE_CARRIER        100.00% null
 12  SCH_OP_CARRIER_AIRLINE_ID    100.00% null
 13  SCH_OP_CARRIER               100.00% null
 14  SCH_OP_CARRIER_FL_NUM        100.00% null
 15  OP_UNIQUE_CARRIER              0.00% null
 16  OP_CARRIER_AIRLINE_ID          0.00% null
 17  OP_CARRIER                     0.00% null
 18  TAIL_NUM                       0.33% null
 19  OP_CARRIER_FL_NUM              0.00% null
 20  ORIGIN_AIRPORT_ID              0.00% null
 21  ORIGIN_AIRPORT_SEQ_ID          0.00% null
 22  ORIGIN_CITY_MARKET_ID          0.00% null
 23  ORIGIN                         0.00% null
 24  ORIGIN_CITY_NAME               0.00% null
 25  ORIGIN_STATE_ABR               0.00% null
 26  ORIGIN_STATE_FIPS              0.00% null
 27  ORIGIN_STATE_NM                0.00% null
 28  ORIGIN_WAC                     0.00% null
 29  DEST_AIRPORT_ID                0.00% null
 30  DEST_AIRPORT_SEQ_ID            0.00% null
 31  DEST_CITY_MARKET_ID            0.00% null
 32  DEST                           0.00% null
 33  DEST_CITY_NAME                 0.00% null
 34  DEST_STATE_ABR                 0.00% null
 35  DEST_STATE_FIPS                0.00% null
 36  DEST_STATE_NM                  0.00% null
 37  DEST_WAC                       0.00% null
 38  CRS_DEP_TIME                   0.00% null
 39  DEP_TIME                       1.72% null
 40  DEP_DELAY                      1.72% null
 41  DEP_DELAY_NEW                  1.72% null
 42  DEP_DEL15                      1.72% null
 43  DEP_DELAY_GROUP                1.72% null
 44  DEP_TIME_BLK                   0.00% null
 45  TAXI_OUT                       1.77% null
 46  WHEELS_OFF                     1.77% null
 47  WHEELS_ON                      1.81% null
 48  TAXI_IN                        1.81% null
 49  CRS_ARR_TIME                   0.00% null
 50  ARR_TIME                       1.81% null
 51  ARR_DELAY                      2.04% null
 52  ARR_DELAY_NEW                  2.04% null
 53  ARR_DEL15                      2.04% null
 54  ARR_DELAY_GROUP                2.04% null
 55  ARR_TIME_BLK                   0.00% null
 56  CANCELLED                      0.00% null
 57  CANCELLATION_CODE             98.22% null
 58  DIVERTED                       0.00% null
 59  DUP                           64.06% null
 60  CRS_ELAPSED_TIME               0.00% null
 61  ACTUAL_ELAPSED_TIME            2.04% null
 62  AIR_TIME                       2.04% null
 63  FLIGHTS                        0.00% null
 64  DISTANCE                       0.00% null
 65  DISTANCE_GROUP                 0.00% null
 66  CARRIER_DELAY                 78.94% null
 67  WEATHER_DELAY                 78.94% null
 68  NAS_DELAY                     78.94% null
 69  SECURITY_DELAY                78.94% null
 70  LATE_AIRCRAFT_DELAY           78.94% null
 71  FIRST_DEP_TIME                99.29% null
 72  TOTAL_ADD_GTIME               99.29% null
 73  LONGEST_ADD_GTIME             99.29% null
 74  DIV_AIRPORT_LANDINGS           0.00% null
 75  DIV_REACHED_DEST              99.74% null
 76  DIV_ACTUAL_ELAPSED_TIME       99.76% null
 77  DIV_ARR_DELAY                 99.76% null
 78  DIV_DISTANCE                  99.74% null
 79  DIV1_AIRPORT                  99.73% null
 80  DIV1_AIRPORT_ID               99.73% null
 81  DIV1_AIRPORT_SEQ_ID           99.73% null
 82  DIV1_WHEELS_ON                99.73% null
 83  DIV1_TOTAL_GTIME              99.73% null
 84  DIV1_LONGEST_GTIME            99.73% null
 85  DIV1_WHEELS_OFF               99.76% null
 86  DIV1_TAIL_NUM                 99.76% null
 87  DIV2_AIRPORT                 100.00% null
 88  DIV2_AIRPORT_ID              100.00% null
 89  DIV2_AIRPORT_SEQ_ID          100.00% null
 90  DIV2_WHEELS_ON               100.00% null
 91  DIV2_TOTAL_GTIME             100.00% null
 92  DIV2_LONGEST_GTIME           100.00% null
 93  DIV2_WHEELS_OFF              100.00% null
 94  DIV2_TAIL_NUM                100.00% null
 95  DIV3_AIRPORT                 100.00% null
 96  DIV3_AIRPORT_ID              100.00% null
 97  DIV3_AIRPORT_SEQ_ID          100.00% null
 98  DIV3_WHEELS_ON               100.00% null
 99  DIV3_TOTAL_GTIME             100.00% null
100  DIV3_LONGEST_GTIME           100.00% null
101  DIV3_WHEELS_OFF              100.00% null
102  DIV3_TAIL_NUM                100.00% null
103  DIV4_AIRPORT                 100.00% null
104  DIV4_AIRPORT_ID              100.00% null
105  DIV4_AIRPORT_SEQ_ID          100.00% null
106  DIV4_WHEELS_ON               100.00% null
107  DIV4_TOTAL_GTIME             100.00% null
108  DIV4_LONGEST_GTIME           100.00% null
109  DIV4_WHEELS_OFF              100.00% null
110  DIV4_TAIL_NUM                100.00% null
111  DIV5_AIRPORT                 100.00% null
112  DIV5_AIRPORT_ID              100.00% null
113  DIV5_AIRPORT_SEQ_ID          100.00% null
114  DIV5_WHEELS_ON               100.00% null
115  DIV5_TOTAL_GTIME             100.00% null
116  DIV5_LONGEST_GTIME           100.00% null
117  DIV5_WHEELS_OFF              100.00% null
118  DIV5_TAIL_NUM                100.00% null

In [3]:
drop_cols = [n for n in names if nulls[n] / total >= 0.99]
keep_cols = [n for n in names if n not in drop_cols]
print(f"Drop {len(drop_cols)} | Keep {len(keep_cols)}")
print(drop_cols)

Drop 51 | Keep 68
['SCH_OP_UNIQUE_CARRIER', 'SCH_OP_CARRIER_AIRLINE_ID', 'SCH_OP_CARRIER', 'SCH_OP_CARRIER_FL_NUM', 'FIRST_DEP_TIME', 'TOTAL_ADD_GTIME', 'LONGEST_ADD_GTIME', 'DIV_REACHED_DEST', 'DIV_ACTUAL_ELAPSED_TIME', 'DIV_ARR_DELAY', 'DIV_DISTANCE', 'DIV1_AIRPORT', 'DIV1_AIRPORT_ID', 'DIV1_AIRPORT_SEQ_ID', 'DIV1_WHEELS_ON', 'DIV1_TOTAL_GTIME', 'DIV1_LONGEST_GTIME', 'DIV1_WHEELS_OFF', 'DIV1_TAIL_NUM', 'DIV2_AIRPORT', 'DIV2_AIRPORT_ID', 'DIV2_AIRPORT_SEQ_ID', 'DIV2_WHEELS_ON', 'DIV2_TOTAL_GTIME', 'DIV2_LONGEST_GTIME', 'DIV2_WHEELS_OFF', 'DIV2_TAIL_NUM', 'DIV3_AIRPORT', 'DIV3_AIRPORT_ID', 'DIV3_AIRPORT_SEQ_ID', 'DIV3_WHEELS_ON', 'DIV3_TOTAL_GTIME', 'DIV3_LONGEST_GTIME', 'DIV3_WHEELS_OFF', 'DIV3_TAIL_NUM', 'DIV4_AIRPORT', 'DIV4_AIRPORT_ID', 'DIV4_AIRPORT_SEQ_ID', 'DIV4_WHEELS_ON', 'DIV4_TOTAL_GTIME', 'DIV4_LONGEST_GTIME', 'DIV4_WHEELS_OFF', 'DIV4_TAIL_NUM', 'DIV5_AIRPORT', 'DIV5_AIRPORT_ID', 'DIV5_AIRPORT_SEQ_ID', 'DIV5_WHEELS_ON', 'DIV5_TOTAL_GTIME', 'DIV5_LONGEST_GTIME', 'DIV5_WHEELS_OFF', 'DIV5_TAIL_NUM']

In [4]:
import time
text_cols = ["MKT_UNIQUE_CARRIER","BRANDED_CODE_SHARE","MKT_CARRIER","OP_UNIQUE_CARRIER","OP_CARRIER",
             "TAIL_NUM","ORIGIN","ORIGIN_CITY_NAME","ORIGIN_STATE_ABR","ORIGIN_STATE_NM",
             "DEST","DEST_CITY_NAME","DEST_STATE_ABR","DEST_STATE_NM","FL_DATE",
             "DEP_TIME_BLK","ARR_TIME_BLK","CANCELLATION_CODE","DUP"]
text_cols = [c for c in text_cols if c in keep_cols]
out_path = "/kaggle/working/flights_typed.parquet"

writer, t0, n = None, time.time(), 0
for batch in pf.iter_batches(batch_size=1_000_000, columns=keep_cols):
    arrays = [batch.column(c) if c in text_cols else pc.cast(batch.column(c), pa.float32()) for c in keep_cols]
    tbl = pa.Table.from_arrays(arrays, names=keep_cols)
    if writer is None:
        writer = pq.ParquetWriter(out_path, tbl.schema, compression="snappy")
    writer.write_table(tbl)
    n += len(tbl); print(f"{n:,} rows | {time.time()-t0:.0f}s")
writer.close()

1,000,000 rows | 25s
2,000,000 rows | 49s
3,000,000 rows | 73s
4,000,000 rows | 98s
5,000,000 rows | 122s
6,000,000 rows | 145s
7,000,000 rows | 168s
8,000,000 rows | 191s
9,000,000 rows | 215s
10,000,000 rows | 238s
11,000,000 rows | 261s
12,000,000 rows | 284s
13,000,000 rows | 305s
14,000,000 rows | 324s
15,000,000 rows | 344s
16,000,000 rows | 361s
17,000,000 rows | 381s
18,000,000 rows | 402s
19,000,000 rows | 423s
20,000,000 rows | 443s
21,000,000 rows | 459s
22,000,000 rows | 481s
23,000,000 rows | 501s
24,000,000 rows | 522s
25,000,000 rows | 544s
26,000,000 rows | 562s
27,000,000 rows | 583s
28,000,000 rows | 604s
29,000,000 rows | 626s
30,000,000 rows | 646s
31,000,000 rows | 663s
32,000,000 rows | 685s
32,957,871 rows | 702s

In [1]:
import gc
import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

In [ ]:
df = pq.read_table(out_path, read_dictionary=text_cols).to_pandas()

In [6]:
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,...,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS
0,2022.0,1.0,1.0,1.0,6.0,1/1/2022 12:00:00 AM,AA,AA,19805.0,AA,...,347.0,1.0,2475.0,10.0,NaN,NaN,NaN,NaN,NaN,0.0
1,2022.0,1.0,1.0,1.0,6.0,1/1/2022 12:00:00 AM,AA,AA,19805.0,AA,...,270.0,1.0,2475.0,10.0,NaN,NaN,NaN,NaN,NaN,0.0
2,2022.0,1.0,1.0,1.0,6.0,1/1/2022 12:00:00 AM,AA,AA,19805.0,AA,...,NaN,1.0,258.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0
3,2022.0,1.0,1.0,1.0,6.0,1/1/2022 12:00:00 AM,AA,AA,19805.0,AA,...,166.0,1.0,1182.0,5.0,907.0,0.0,3.0,0.0,0.0,0.0
4,2022.0,1.0,1.0,1.0,6.0,1/1/2022 12:00:00 AM,AA,AA,19805.0,AA,...,104.0,1.0,575.0,3.0,16.0,0.0,0.0,0.0,3.0,0.0

In [10]:
info = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "null_%": (df.isna().mean() * 100).round(2),
    "nunique": df.nunique(),
    "MB": (df.memory_usage(deep=True) / 1e6).round(0),
})
print(f"Total: {info['MB'].sum()/1e3:.1f} GB")
info

Total: 7.3 GB

                       dtype  null_%  nunique     MB
ACTUAL_ELAPSED_TIME  float32    2.04    749.0  132.0
AIR_TIME             float32    2.04    701.0  132.0
ARR_DEL15            float32    2.04      2.0  132.0
ARR_DELAY            float32    2.04   2428.0  132.0
ARR_DELAY_GROUP      float32    2.04     15.0  132.0
...                      ...     ...      ...    ...
TAXI_OUT             float32    1.77    217.0  132.0
WEATHER_DELAY        float32   78.94   1441.0  132.0
WHEELS_OFF           float32    1.77   1440.0  132.0
WHEELS_ON            float32    1.81   1440.0  132.0
YEAR                 float32    0.00      5.0  132.0

[69 rows x 4 columns]

In [13]:
num_cols = df.select_dtypes("number").columns
info["min"] = df[num_cols].min()
info["max"] = df[num_cols].max()
info["range"] = info["min"].astype(str) + "  to  " + info["max"].astype(str)
info.loc[info["min"].isna(), "range"] = ""            # text/category columns
info["whole_nums"] = pd.Series({c: bool((df[c].dropna() % 1 == 0).all()) for c in num_cols})

pd.set_option("display.max_rows", None, "display.width", 200)
print(info[["dtype", "null_%", "nunique", "range", "whole_nums", "MB"]].to_string())

                           dtype  null_%  nunique                     range whole_nums     MB
ACTUAL_ELAPSED_TIME      float32    2.04    749.0           14.0  to  965.0       True  132.0
AIR_TIME                 float32    2.04    701.0            5.0  to  953.0       True  132.0
ARR_DEL15                float32    2.04      2.0              0.0  to  1.0       True  132.0
ARR_DELAY                float32    2.04   2428.0        -128.0  to  7232.0       True  132.0
ARR_DELAY_GROUP          float32    2.04     15.0            -2.0  to  12.0       True  132.0
ARR_DELAY_NEW            float32    2.04   2322.0           0.0  to  7232.0       True  132.0
ARR_TIME                 float32    1.81   1440.0           1.0  to  2400.0       True  132.0
ARR_TIME_BLK            category    0.00     19.0                                  NaN   33.0
BRANDED_CODE_SHARE      category   64.06     14.0                                  NaN   33.0
CANCELLATION_CODE       category   98.22      4.0                                  NaN   33.0
CANCELLED                float32    0.00      2.0              0.0  to  1.0       True  132.0
CARRIER_DELAY            float32   78.94   2204.0           0.0  to  7232.0       True  132.0
CRS_ARR_TIME             float32    0.00   1440.0           1.0  to  2400.0       True  132.0
CRS_DEP_TIME             float32    0.00   1422.0           1.0  to  2400.0       True  132.0
CRS_ELAPSED_TIME         float32    0.00    705.0        -272.0  to  1510.0       True  132.0
DAY_OF_MONTH             float32    0.00     31.0             1.0  to  31.0       True  132.0
DAY_OF_WEEK              float32    0.00      7.0              1.0  to  7.0       True  132.0
DEP_DEL15                float32    1.72      2.0              0.0  to  1.0       True  132.0
DEP_DELAY                float32    1.72   2410.0        -115.0  to  7223.0       True  132.0
DEP_DELAY_GROUP          float32    1.72     15.0            -2.0  to  12.0       True  132.0
DEP_DELAY_NEW            float32    1.72   2326.0           0.0  to  7223.0       True  132.0
DEP_TIME                 float32    1.72   1440.0           1.0  to  2400.0       True  132.0
DEP_TIME_BLK            category    0.00     19.0                                  NaN   33.0
DEST                    category    0.00    385.0                                  NaN   66.0
DEST_AIRPORT_ID          float32    0.00    384.0      10135.0  to  16869.0       True  132.0
DEST_AIRPORT_SEQ_ID      float32    0.00    604.0  1013506.0  to  1686902.0       True  132.0
DEST_CITY_MARKET_ID      float32    0.00    360.0      30070.0  to  36422.0       True  132.0
DEST_CITY_NAME          category    0.00    378.0                                  NaN   66.0
DEST_STATE_ABR          category    0.00     53.0                                  NaN   33.0
DEST_STATE_FIPS          float32    0.00     53.0             1.0  to  78.0       True  132.0
DEST_STATE_NM           category    0.00     53.0                                  NaN   33.0
DEST_WAC                 float32    0.00     53.0             1.0  to  93.0       True  132.0
DISTANCE                 float32    0.00   1821.0          11.0  to  5095.0       True  132.0
DISTANCE_GROUP           float32    0.00     11.0             1.0  to  11.0       True  132.0
DIVERTED                 float32    0.00      2.0              0.0  to  1.0       True  132.0
DIV_AIRPORT_LANDINGS     float32    0.00      5.0              0.0  to  9.0       True  132.0
DUP                     category   64.06      1.0                                  NaN   33.0
FLIGHTS                  float32    0.00      1.0              1.0  to  1.0       True  132.0
FL_DATE                 category    0.00   1704.0                                  NaN   66.0
Index                        NaN     NaN      NaN                                  NaN    0.0
LATE_AIRCRAFT_DELAY      float32   78.94   1706.0           0.0  to  3581.0       True  132.0
MKT_CARRIER             category   64.06     10.0                                  NaN   33.0
MKT_CARRIER_AIRLINE_ID   float32   64.06     10.0      19393.0  to  20436.0       True  132.0
MKT_CARRIER_FL_NUM       float32   64.06   6874.0           1.0  to  9887.0       True  132.0
MKT_UNIQUE_CARRIER      category   64.06     10.0                                  NaN   33.0
MONTH                    float32    0.00     12.0             1.0  to  12.0       True  132.0
NAS_DELAY                float32   78.94   1264.0           0.0  to  2700.0       True  132.0
OP_CARRIER              category    0.00     21.0                                  NaN   33.0
OP_CARRIER_AIRLINE_ID    float32    0.00     21.0      19393.0  to  20500.0       True  132.0
OP_CARRIER_FL_NUM        float32    0.00   7074.0           1.0  to  9914.0       True  132.0
OP_UNIQUE_CARRIER       category    0.00     21.0                                  NaN   33.0
ORIGIN                  category    0.00    384.0                                  NaN   66.0
ORIGIN_AIRPORT_ID        float32    0.00    383.0      10135.0  to  16869.0       True  132.0
ORIGIN_AIRPORT_SEQ_ID    float32    0.00    603.0  1013506.0  to  1686902.0       True  132.0
ORIGIN_CITY_MARKET_ID    float32    0.00    359.0      30070.0  to  36422.0       True  132.0
ORIGIN_CITY_NAME        category    0.00    377.0                                  NaN   66.0
ORIGIN_STATE_ABR        category    0.00     53.0                                  NaN   33.0
ORIGIN_STATE_FIPS        float32    0.00     53.0             1.0  to  78.0       True  132.0
ORIGIN_STATE_NM         category    0.00     53.0                                  NaN   33.0
ORIGIN_WAC               float32    0.00     53.0             1.0  to  93.0       True  132.0
QUARTER                  float32    0.00      4.0              1.0  to  4.0       True  132.0
SECURITY_DELAY           float32   78.94    337.0           0.0  to  1600.0       True  132.0
TAIL_NUM                category    0.33   7564.0                                  NaN   67.0
TAXI_IN                  float32    1.81    298.0           1.0  to  1318.0       True  132.0
TAXI_OUT                 float32    1.77    217.0           1.0  to  1274.0       True  132.0
WEATHER_DELAY            float32   78.94   1441.0           0.0  to  2394.0       True  132.0
WHEELS_OFF               float32    1.77   1440.0           1.0  to  2400.0       True  132.0
WHEELS_ON                float32    1.81   1440.0           1.0  to  2400.0       True  132.0
YEAR                     float32    0.00      5.0        2022.0  to  2026.0       True  132.0

In [14]:
i8  = ["QUARTER","MONTH","DAY_OF_MONTH","DAY_OF_WEEK","CANCELLED","DIVERTED","DISTANCE_GROUP",
       "DIV_AIRPORT_LANDINGS","FLIGHTS","ORIGIN_STATE_FIPS","DEST_STATE_FIPS","ORIGIN_WAC","DEST_WAC"]
i16 = ["YEAR","CRS_DEP_TIME","CRS_ARR_TIME","CRS_ELAPSED_TIME","DISTANCE","OP_CARRIER_FL_NUM",
       "OP_CARRIER_AIRLINE_ID","ORIGIN_AIRPORT_ID","DEST_AIRPORT_ID"]
u16 = ["ORIGIN_CITY_MARKET_ID","DEST_CITY_MARKET_ID"]              # max 36,422 > int16 limit
i32 = ["ORIGIN_AIRPORT_SEQ_ID","DEST_AIRPORT_SEQ_ID"]              # ~1.6M
# columns with nulls -> pandas nullable ints
n8  = ["DEP_DEL15","DEP_DELAY_GROUP","ARR_DEL15","ARR_DELAY_GROUP"]
n16 = ["DEP_TIME","ARR_TIME","WHEELS_OFF","WHEELS_ON","TAXI_OUT","TAXI_IN","AIR_TIME","ACTUAL_ELAPSED_TIME",
       "DEP_DELAY_NEW","ARR_DELAY","ARR_DELAY_NEW","CARRIER_DELAY","WEATHER_DELAY","NAS_DELAY",
       "SECURITY_DELAY","LATE_AIRCRAFT_DELAY","MKT_CARRIER_FL_NUM"]
nu16 = ["MKT_CARRIER_AIRLINE_ID"]

plan = {**dict.fromkeys(i8,"int8"), **dict.fromkeys(i16,"int16"), **dict.fromkeys(u16,"uint16"),
        **dict.fromkeys(i32,"int32"), **dict.fromkeys(n8,"Int8"), **dict.fromkeys(n16,"Int16"),
        **dict.fromkeys(nu16,"UInt16")}

before = df.memory_usage(deep=True).sum()/1e9
for c, t in plan.items():
    df[c] = df[c].astype(t)
gc.collect()
print(f"{before:.1f} GB -> {df.memory_usage(deep=True).sum()/1e9:.1f} GB")
print(df.dtypes.value_counts())

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [15]:
bad = [c for c, t in plan.items() if t[0].islower() and df[c].isna().any()]
print("Columns with hidden nulls:", bad)
for c in bad:
    plan[c] = plan[c].replace("uint", "UInt").replace("int", "Int")   # int16 -> Int16, uint16 -> UInt16

before = df.memory_usage(deep=True).sum()/1e9
for c, t in plan.items():
    if str(df[c].dtype) != t:
        df[c] = df[c].astype(t)
gc.collect()
print(f"{before:.1f} GB -> {df.memory_usage(deep=True).sum()/1e9:.1f} GB")
print(df.dtypes.value_counts())

Columns with hidden nulls: ['DIV_AIRPORT_LANDINGS', 'CRS_ELAPSED_TIME', 'OP_CARRIER_FL_NUM']
6.6 GB -> 4.5 GB
Int16       19
int8        12
int16        7
Int8         5
category     2
int32        2
category     2
category     2
category     2
category     2
uint16       2
UInt16       1
category     1
category     1
category     1
category     1
category     1
category     1
float32      1
category     1
category     1
category     1
Name: count, dtype: int64

In [16]:
print(pd.crosstab(df["DEP_DELAY"].isna(), [df["CANCELLED"], df["DIVERTED"]], margins=True))

CANCELLED         0              1       All
DIVERTED          0      1       0
DEP_DELAY
False      32284613  86850   19447  32390910
True              0      0  566961    566961
All        32284613  86850  586408  32957871

In [18]:

df.dtypes

YEAR                         int16
QUARTER                       int8
MONTH                         int8
DAY_OF_MONTH                  int8
DAY_OF_WEEK                   int8
FL_DATE                   category
MKT_UNIQUE_CARRIER        category
BRANDED_CODE_SHARE        category
MKT_CARRIER_AIRLINE_ID      UInt16
MKT_CARRIER               category
MKT_CARRIER_FL_NUM           Int16
OP_UNIQUE_CARRIER         category
OP_CARRIER_AIRLINE_ID        int16
OP_CARRIER                category
TAIL_NUM                  category
OP_CARRIER_FL_NUM            Int16
ORIGIN_AIRPORT_ID            int16
ORIGIN_AIRPORT_SEQ_ID        int32
ORIGIN_CITY_MARKET_ID       uint16
ORIGIN                    category
ORIGIN_CITY_NAME          category
ORIGIN_STATE_ABR          category
ORIGIN_STATE_FIPS             int8
ORIGIN_STATE_NM           category
ORIGIN_WAC                    int8
DEST_AIRPORT_ID              int16
DEST_AIRPORT_SEQ_ID          int32
DEST_CITY_MARKET_ID         uint16
DEST                      category
DEST_CITY_NAME            category
DEST_STATE_ABR            category
DEST_STATE_FIPS               int8
DEST_STATE_NM             category
DEST_WAC                      int8
CRS_DEP_TIME                 int16
DEP_TIME                     Int16
DEP_DELAY                  float32
DEP_DELAY_NEW                Int16
DEP_DEL15                     Int8
DEP_DELAY_GROUP               Int8
DEP_TIME_BLK              category
TAXI_OUT                     Int16
WHEELS_OFF                   Int16
WHEELS_ON                    Int16
TAXI_IN                      Int16
CRS_ARR_TIME                 int16
ARR_TIME                     Int16
ARR_DELAY                    Int16
ARR_DELAY_NEW                Int16
ARR_DEL15                     Int8
ARR_DELAY_GROUP               Int8
ARR_TIME_BLK              category
CANCELLED                     int8
CANCELLATION_CODE         category
DIVERTED                      int8
DUP                       category
CRS_ELAPSED_TIME             Int16
ACTUAL_ELAPSED_TIME          Int16
AIR_TIME                     Int16
FLIGHTS                       int8
DISTANCE                     int16
DISTANCE_GROUP                int8
CARRIER_DELAY                Int16
WEATHER_DELAY                Int16
NAS_DELAY                    Int16
SECURITY_DELAY               Int16
LATE_AIRCRAFT_DELAY          Int16
DIV_AIRPORT_LANDINGS          Int8
dtype: object

In [19]:
df.to_parquet("/kaggle/working/flights_df_68cols.parquet", compression="snappy", index=False)
import os; print(f"{os.path.getsize('/kaggle/working/flights_df_68cols.parquet')/1e9:.2f} GB saved")

1.51 GB saved

In [20]:
from IPython.display import FileLink
FileLink("flights_df_68cols.parquet")

/kaggle/working/flights_df_68cols.parquet

----------------------------------------------------------------------------------------------------

In [1]:
import pandas as pd

path = "/kaggle/input/datasets/tjaycuz/68-col-v2/flights_df_68cols (1).parquet"
df = pd.read_parquet(path)
print(df.shape)

num = df.select_dtypes("number")
summary = pd.DataFrame({"dtype": df.dtypes.astype(str)})
summary["min"] = num.min()
summary["max"] = num.max()
summary["nulls"] = df.isna().sum()
pd.set_option("display.max_rows", None)
summary

(32957871, 68)

                           dtype        min        max     nulls
YEAR                       int16     2022.0     2026.0         0
QUARTER                     int8        1.0        4.0         0
MONTH                       int8        1.0       12.0         0
DAY_OF_MONTH                int8        1.0       31.0         0
DAY_OF_WEEK                 int8        1.0        7.0         0
FL_DATE                 category       <NA>       <NA>         0
MKT_UNIQUE_CARRIER      category       <NA>       <NA>  21111909
BRANDED_CODE_SHARE      category       <NA>       <NA>  21111909
MKT_CARRIER_AIRLINE_ID    UInt16    19393.0    20436.0  21111909
MKT_CARRIER             category       <NA>       <NA>  21111909
MKT_CARRIER_FL_NUM         Int16        1.0     9887.0  21111909
OP_UNIQUE_CARRIER       category       <NA>       <NA>         0
OP_CARRIER_AIRLINE_ID      int16    19393.0    20500.0         0
OP_CARRIER              category       <NA>       <NA>         0
TAIL_NUM                category       <NA>       <NA>    108666
OP_CARRIER_FL_NUM          Int16        1.0     9914.0         1
ORIGIN_AIRPORT_ID          int16    10135.0    16869.0         0
ORIGIN_AIRPORT_SEQ_ID      int32  1013506.0  1686902.0         0
ORIGIN_CITY_MARKET_ID     uint16    30070.0    36422.0         0
ORIGIN                  category       <NA>       <NA>         0
ORIGIN_CITY_NAME        category       <NA>       <NA>         0
ORIGIN_STATE_ABR        category       <NA>       <NA>         0
ORIGIN_STATE_FIPS           int8        1.0       78.0         0
ORIGIN_STATE_NM         category       <NA>       <NA>         0
ORIGIN_WAC                  int8        1.0       93.0         0
DEST_AIRPORT_ID            int16    10135.0    16869.0         0
DEST_AIRPORT_SEQ_ID        int32  1013506.0  1686902.0         0
DEST_CITY_MARKET_ID       uint16    30070.0    36422.0         0
DEST                    category       <NA>       <NA>         0
DEST_CITY_NAME          category       <NA>       <NA>         0
DEST_STATE_ABR          category       <NA>       <NA>         0
DEST_STATE_FIPS             int8        1.0       78.0         0
DEST_STATE_NM           category       <NA>       <NA>         0
DEST_WAC                    int8        1.0       93.0         0
CRS_DEP_TIME               int16        1.0     2400.0         0
DEP_TIME                   Int16        1.0     2400.0    565656
DEP_DELAY                float32     -115.0     7223.0    566961
DEP_DELAY_NEW              Int16        0.0     7223.0    566961
DEP_DEL15                   Int8        0.0        1.0    566961
DEP_DELAY_GROUP             Int8       -2.0       12.0    566961
DEP_TIME_BLK            category       <NA>       <NA>         0
TAXI_OUT                   Int16        1.0     1274.0    583079
WHEELS_OFF                 Int16        1.0     2400.0    583079
WHEELS_ON                  Int16        1.0     2400.0    595408
TAXI_IN                    Int16        1.0     1318.0    595408
CRS_ARR_TIME               int16        1.0     2400.0         0
ARR_TIME                   Int16        1.0     2400.0    595402
ARR_DELAY                  Int16     -128.0     7232.0    673261
ARR_DELAY_NEW              Int16        0.0     7232.0    673261
ARR_DEL15                   Int8        0.0        1.0    673261
ARR_DELAY_GROUP             Int8       -2.0       12.0    673261
ARR_TIME_BLK            category       <NA>       <NA>         0
CANCELLED                   int8        0.0        1.0         0
CANCELLATION_CODE       category       <NA>       <NA>  32371463
DIVERTED                    int8        0.0        1.0         0
DUP                     category       <NA>       <NA>  21111909
CRS_ELAPSED_TIME           Int16     -272.0     1510.0        10
ACTUAL_ELAPSED_TIME        Int16       14.0      965.0    673261
AIR_TIME                   Int16        5.0      953.0    673261
FLIGHTS                     int8        1.0        1.0         0
DISTANCE                   int16       11.0     5095.0         0
DISTANCE_GROUP              int8        1.0       11.0         0
CARRIER_DELAY              Int16        0.0     7232.0  26016708
WEATHER_DELAY              Int16        0.0     2394.0  26016708
NAS_DELAY                  Int16        0.0     2700.0  26016708
SECURITY_DELAY             Int16        0.0     1600.0  26016708
LATE_AIRCRAFT_DELAY        Int16        0.0     3581.0  26016708
DIV_AIRPORT_LANDINGS        Int8        0.0        9.0         8

In [2]:
pd.set_option("display.max_rows", None)

summary

                           dtype        min        max     nulls
YEAR                       int16     2022.0     2026.0         0
QUARTER                     int8        1.0        4.0         0
MONTH                       int8        1.0       12.0         0
DAY_OF_MONTH                int8        1.0       31.0         0
DAY_OF_WEEK                 int8        1.0        7.0         0
FL_DATE                 category       <NA>       <NA>         0
MKT_UNIQUE_CARRIER      category       <NA>       <NA>  21111909
BRANDED_CODE_SHARE      category       <NA>       <NA>  21111909
MKT_CARRIER_AIRLINE_ID    UInt16    19393.0    20436.0  21111909
MKT_CARRIER             category       <NA>       <NA>  21111909
MKT_CARRIER_FL_NUM         Int16        1.0     9887.0  21111909
OP_UNIQUE_CARRIER       category       <NA>       <NA>         0
OP_CARRIER_AIRLINE_ID      int16    19393.0    20500.0         0
OP_CARRIER              category       <NA>       <NA>         0
TAIL_NUM                category       <NA>       <NA>    108666
OP_CARRIER_FL_NUM          Int16        1.0     9914.0         1
ORIGIN_AIRPORT_ID          int16    10135.0    16869.0         0
ORIGIN_AIRPORT_SEQ_ID      int32  1013506.0  1686902.0         0
ORIGIN_CITY_MARKET_ID     uint16    30070.0    36422.0         0
ORIGIN                  category       <NA>       <NA>         0
ORIGIN_CITY_NAME        category       <NA>       <NA>         0
ORIGIN_STATE_ABR        category       <NA>       <NA>         0
ORIGIN_STATE_FIPS           int8        1.0       78.0         0
ORIGIN_STATE_NM         category       <NA>       <NA>         0
ORIGIN_WAC                  int8        1.0       93.0         0
DEST_AIRPORT_ID            int16    10135.0    16869.0         0
DEST_AIRPORT_SEQ_ID        int32  1013506.0  1686902.0         0
DEST_CITY_MARKET_ID       uint16    30070.0    36422.0         0
DEST                    category       <NA>       <NA>         0
DEST_CITY_NAME          category       <NA>       <NA>         0
DEST_STATE_ABR          category       <NA>       <NA>         0
DEST_STATE_FIPS             int8        1.0       78.0         0
DEST_STATE_NM           category       <NA>       <NA>         0
DEST_WAC                    int8        1.0       93.0         0
CRS_DEP_TIME               int16        1.0     2400.0         0
DEP_TIME                   Int16        1.0     2400.0    565656
DEP_DELAY                float32     -115.0     7223.0    566961
DEP_DELAY_NEW              Int16        0.0     7223.0    566961
DEP_DEL15                   Int8        0.0        1.0    566961
DEP_DELAY_GROUP             Int8       -2.0       12.0    566961
DEP_TIME_BLK            category       <NA>       <NA>         0
TAXI_OUT                   Int16        1.0     1274.0    583079
WHEELS_OFF                 Int16        1.0     2400.0    583079
WHEELS_ON                  Int16        1.0     2400.0    595408
TAXI_IN                    Int16        1.0     1318.0    595408
CRS_ARR_TIME               int16        1.0     2400.0         0
ARR_TIME                   Int16        1.0     2400.0    595402
ARR_DELAY                  Int16     -128.0     7232.0    673261
ARR_DELAY_NEW              Int16        0.0     7232.0    673261
ARR_DEL15                   Int8        0.0        1.0    673261
ARR_DELAY_GROUP             Int8       -2.0       12.0    673261
ARR_TIME_BLK            category       <NA>       <NA>         0
CANCELLED                   int8        0.0        1.0         0
CANCELLATION_CODE       category       <NA>       <NA>  32371463
DIVERTED                    int8        0.0        1.0         0
DUP                     category       <NA>       <NA>  21111909
CRS_ELAPSED_TIME           Int16     -272.0     1510.0        10
ACTUAL_ELAPSED_TIME        Int16       14.0      965.0    673261
AIR_TIME                   Int16        5.0      953.0    673261
FLIGHTS                     int8        1.0        1.0         0
DISTANCE                   int16       11.0     5095.0         0
DISTANCE_GROUP              int8        1.0       11.0         0
CARRIER_DELAY              Int16        0.0     7232.0  26016708
WEATHER_DELAY              Int16        0.0     2394.0  26016708
NAS_DELAY                  Int16        0.0     2700.0  26016708
SECURITY_DELAY             Int16        0.0     1600.0  26016708
LATE_AIRCRAFT_DELAY        Int16        0.0     3581.0  26016708
DIV_AIRPORT_LANDINGS        Int8        0.0        9.0         8

In [3]:
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"].astype(str))
print(df["FL_DATE"].min(), df["FL_DATE"].max())

bad = df[df["CRS_ELAPSED_TIME"] <= 0]
print(len(bad))
bad[["FL_DATE","OP_UNIQUE_CARRIER","ORIGIN","DEST","CRS_DEP_TIME","CRS_ARR_TIME","CRS_ELAPSED_TIME","DISTANCE"]].head(20)

/tmp/ipykernel_49/1946666277.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["FL_DATE"] = pd.to_datetime(df["FL_DATE"].astype(str))

2022-01-01 00:00:00 2026-08-31 00:00:00
21

,FL_DATE,OP_UNIQUE_CARRIER,ORIGIN,DEST,CRS_DEP_TIME,CRS_ARR_TIME,CRS_ELAPSED_TIME,DISTANCE
378148,2022-01-21,YX,BNA,EWR,600,922,-48,748
5533880,2022-10-14,YX,IND,LGA,605,811,-44,660
5706328,2022-10-23,YX,PIT,BOS,825,804,-36,496
6539245,2022-12-06,YX,PIT,BOS,605,805,-85,496
8570162,2023-03-23,YX,JFK,PWM,2240,2235,-5,273
13827657,2023-12-14,OO,DFW,GCK,1353,921,-272,404
15724889,2024-03-27,WN,LAS,RNO,1840,1600,-160,345
27394292,2025-11-17,WN,LAS,BUR,1724,1545,-99,223
27394416,2025-11-17,WN,LAS,BUR,1802,1655,-67,223
27426411,2025-11-19,OO,DTW,LEX,1053,953,-60,296
27449493,2025-11-20,WN,HOU,DAL,1635,1510,-85,239
28039208,2025-12-21,WN,HOU,HRL,56,2355,-61,277
28243630,2026-01-01,WN,PHX,LAS,2140,2105,-64,255
28476343,2026-01-14,WN,DAL,SAT,1446,1430,-16,247
28495952,2026-01-15,WN,STL,DSM,2229,2215,-14,259
28635267,2026-01-23,WN,BWI,MHT,1254,1210,-44,377
29076005,2026-02-17,WN,OAK,BUR,2215,2110,-65,325
29359143,2026-03-04,WN,SAT,DAL,1950,1825,-85,247
29538577,2026-03-13,WN,BWI,ROC,12,2355,-17,277
29597845,2026-03-16,WN,GSP,BNA,2012,1855,-17,265

----------------------------------------------------------------------------------------------------

### Project begins

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
path = "/kaggle/input/datasets/tjaycuz/68-col-v2/flights_df_68cols (1).parquet"
df = pd.read_parquet(path)

In [8]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 250)
pd.options.display.float_format = '{:,.2f}'.format


df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,MKT_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,DUP,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS
0,2022,1,1,1,6,1/1/2022 12:00:00 AM,AA,AA,19805,AA,1,AA,19805,AA,N106NN,1,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,22,12892,1289208,32575,LAX,"Los Angeles, CA",CA,6,California,91,700,657,-3.00,0,0,-1,0700-0759,19,716,1003,9,1029,1012,-17,0,0,-2,1000-1059,0,NaN,0,N,389,375,347,1,2475,10,<NA>,<NA>,<NA>,<NA>,<NA>,0
1,2022,1,1,1,6,1/1/2022 12:00:00 AM,AA,AA,19805,AA,10,AA,19805,AA,N101NN,10,12892,1289208,32575,LAX,"Los Angeles, CA",CA,6,California,91,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,22,900,857,-3.00,0,0,-1,0900-0959,20,917,1647,16,1724,1703,-21,0,0,-2,1700-1759,0,NaN,0,N,324,306,270,1,2475,10,<NA>,<NA>,<NA>,<NA>,<NA>,0
2,2022,1,1,1,6,1/1/2022 12:00:00 AM,AA,AA,19805,AA,1003,AA,19805,AA,N830NN,1003,15016,1501606,31123,STL,"St. Louis, MO",MO,29,Missouri,64,13930,1393007,30977,ORD,"Chicago, IL",IL,17,Illinois,41,705,<NA>,NaN,<NA>,<NA>,<NA>,0700-0759,<NA>,<NA>,<NA>,<NA>,831,<NA>,<NA>,<NA>,<NA>,<NA>,0800-0859,1,B,0,N,86,<NA>,<NA>,1,258,2,<NA>,<NA>,<NA>,<NA>,<NA>,0
3,2022,1,1,1,6,1/1/2022 12:00:00 AM,AA,AA,19805,AA,1004,AA,19805,AA,N805NN,1004,13930,1393007,30977,ORD,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,FLL,"Fort Lauderdale, FL",FL,12,Florida,33,1830,937,907.00,907,1,12,1800-1859,23,1000,1346,3,2239,1349,910,910,1,12,2200-2259,0,NaN,0,N,189,192,166,1,1182,5,907,0,3,0,0,0
4,2022,1,1,1,6,1/1/2022 12:00:00 AM,AA,AA,19805,AA,1007,AA,19805,AA,N870NN,1007,11057,1105703,31057,CLT,"Charlotte, NC",NC,37,North Carolina,36,15016,1501606,31123,STL,"St. Louis, MO",MO,29,Missouri,64,2240,2300,20.00,20,1,1,2200-2259,16,2316,2400,4,2345,4,19,19,1,1,2300-2359,0,NaN,0,N,125,124,104,1,575,3,16,0,0,0,3,0

In [4]:
df.tail()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,MKT_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,DUP,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS
32957866,2026,3,8,31,1,8/31/2026 12:00:00 AM,NaN,NaN,<NA>,NaN,<NA>,YX,20452,YX,N979RP,4351,10994,1099402,30994,CHS,"Charleston, SC",SC,45,South Carolina,37,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,1751,1748,-3.0,0,0,-1,1700-1759,15,1803,1932,6,2000,1938,-22,0,0,-2,2000-2059,0,NaN,0,NaN,129,110,89,1,641,3,<NA>,<NA>,<NA>,<NA>,<NA>,0
32957867,2026,3,8,31,1,8/31/2026 12:00:00 AM,NaN,NaN,<NA>,NaN,<NA>,YX,20452,YX,N979RP,4567,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,10994,1099402,30994,CHS,"Charleston, SC",SC,45,South Carolina,37,1459,1450,-9.0,0,0,-1,1400-1459,38,1528,1710,9,1719,1719,0,0,0,0,1700-1759,0,NaN,0,NaN,140,149,102,1,641,3,<NA>,<NA>,<NA>,<NA>,<NA>,0
32957868,2026,3,8,31,1,8/31/2026 12:00:00 AM,NaN,NaN,<NA>,NaN,<NA>,YX,20452,YX,N979RP,4602,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,10994,1099402,30994,CHS,"Charleston, SC",SC,45,South Carolina,37,905,910,5.0,5,0,0,0900-0959,29,939,1110,4,1126,1114,-12,0,0,-1,1100-1159,0,NaN,0,NaN,141,124,91,1,641,3,<NA>,<NA>,<NA>,<NA>,<NA>,0
32957869,2026,3,8,31,1,8/31/2026 12:00:00 AM,NaN,NaN,<NA>,NaN,<NA>,YX,20452,YX,N979RP,4664,10994,1099402,30994,CHS,"Charleston, SC",SC,45,South Carolina,37,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,1200,1158,-2.0,0,0,-1,1200-1259,13,1211,1349,6,1408,1355,-13,0,0,-1,1400-1459,0,NaN,0,NaN,128,117,98,1,641,3,<NA>,<NA>,<NA>,<NA>,<NA>,0
32957870,2026,3,8,31,1,8/31/2026 12:00:00 AM,NaN,NaN,<NA>,NaN,<NA>,YX,20452,YX,N979RP,4809,10397,1039708,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,609,603,-6.0,0,0,-1,0600-0659,16,619,804,8,825,812,-13,0,0,-1,0800-0859,0,NaN,0,NaN,136,129,105,1,762,4,<NA>,<NA>,<NA>,<NA>,<NA>,0

In [5]:
df.shape

(32957871, 68)

In [11]:
df.describe().style.set_sticky(axis="index")

## Functions

In [26]:
"""
basically print the average of all the flights form the year 2022 till 2026 
single average is the output for all the flights, (basically 32957871 / 12)

"""



def calculate_avg_flights_per_month(df):
    count = len(df["MONTH"])
    result = count/12
    return result

avg = calculate_avg_flight_per_month(df)
print(avg)

2746489.25

In [13]:
count = len(df["MONTH"])
print(count)

32957871

In [19]:
df["MONTH"].value_counts().sort_index()

MONTH
1     2768635
2     2595323
3     3011517
4     2941040
5     3046706
6     3045918
7     3155796
8     3083677
9     2294790
10    2415631
11    2277238
12    2321600
Name: count, dtype: int64

## Functions using Groupby

In [41]:

"""
Q . calculates the average number of flight records per year

Hint for groupby syntax is "df.groupby("Categorical_Column")["Numerical_Column"].operation()"
CATEGORICAL col FIRST and then the NUMERICAL cols comes.
"""



def avg_flights_per_year(df):
    yearly_flights = df.groupby("YEAR").size()
    avg = yearly_flights.mean()
    return avg


avg = avg_flights_per_year(df)
print(avg)
print(type(yearly_flights))                                
    

print(f" We have {avg} flights per year")

6591574.2
<class 'pandas.core.series.Series'>
 We have 6591574.2 flights per year

In [37]:
yearly_flights = df.groupby("YEAR").size()
print(yearly_flights)

YEAR
2022    7013508
2023    7134931
2024    7079081
2025    7001619
2026    4728732
dtype: int64

In [46]:
"""
Q. average number of flight records per month across all years

"""


def avg_flights_per_month_across_all_years(df):
    month = df.groupby("MONTH").size()
    avg = month.mean()
    return avg

avg = avg_flights_per_month_across_all_years(df)
print(avg)

2746489.25

In [47]:
a=df.groupby("MONTH").size()
print(a)

MONTH
1     2768635
2     2595323
3     3011517
4     2941040
5     3046706
6     3045918
7     3155796
8     3083677
9     2294790
10    2415631
11    2277238
12    2321600
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32957871 entries, 0 to 32957870
Data columns (total 68 columns):
 #   Column                  Dtype
---  ------                  -----
 0   YEAR                    int16
 1   QUARTER                 int8
 2   MONTH                   int8
 3   DAY_OF_MONTH            int8
 4   DAY_OF_WEEK             int8
 5   FL_DATE                 category
 6   MKT_UNIQUE_CARRIER      category
 7   BRANDED_CODE_SHARE      category
 8   MKT_CARRIER_AIRLINE_ID  UInt16
 9   MKT_CARRIER             category
 10  MKT_CARRIER_FL_NUM      Int16
 11  OP_UNIQUE_CARRIER       category
 12  OP_CARRIER_AIRLINE_ID   int16
 13  OP_CARRIER              category
 14  TAIL_NUM                category
 15  OP_CARRIER_FL_NUM       Int16
 16  ORIGIN_AIRPORT_ID       int16
 17  ORIGIN_AIRPORT_SEQ_ID   int32
 18  ORIGIN_CITY_MARKET_ID   uint16
 19  ORIGIN                  category
 20  ORIGIN_CITY_NAME        category
 21  ORIGIN_STATE_ABR        category
 22  ORIGIN_STATE_FIPS       int8
 23  ORIGIN_STATE_NM         category
 24  ORIGIN_WAC              int8
 25  DEST_AIRPORT_ID         int16
 26  DEST_AIRPORT_SEQ_ID     int32
 27  DEST_CITY_MARKET_ID     uint16
 28  DEST                    category
 29  DEST_CITY_NAME          category
 30  DEST_STATE_ABR          category
 31  DEST_STATE_FIPS         int8
 32  DEST_STATE_NM           category
 33  DEST_WAC                int8
 34  CRS_DEP_TIME            int16
 35  DEP_TIME                Int16
 36  DEP_DELAY               float32
 37  DEP_DELAY_NEW           Int16
 38  DEP_DEL15               Int8
 39  DEP_DELAY_GROUP         Int8
 40  DEP_TIME_BLK            category
 41  TAXI_OUT                Int16
 42  WHEELS_OFF              Int16
 43  WHEELS_ON               Int16
 44  TAXI_IN                 Int16
 45  CRS_ARR_TIME            int16
 46  ARR_TIME                Int16
 47  ARR_DELAY               Int16
 48  ARR_DELAY_NEW           Int16
 49  ARR_DEL15               Int8
 50  ARR_DELAY_GROUP         Int8
 51  ARR_TIME_BLK            category
 52  CANCELLED               int8
 53  CANCELLATION_CODE       category
 54  DIVERTED                int8
 55  DUP                     category
 56  CRS_ELAPSED_TIME        Int16
 57  ACTUAL_ELAPSED_TIME     Int16
 58  AIR_TIME                Int16
 59  FLIGHTS                 int8
 60  DISTANCE                int16
 61  DISTANCE_GROUP          int8
 62  CARRIER_DELAY           Int16
 63  WEATHER_DELAY           Int16
 64  NAS_DELAY               Int16
 65  SECURITY_DELAY          Int16
 66  LATE_AIRCRAFT_DELAY     Int16
 67  DIV_AIRPORT_LANDINGS    Int8
dtypes: Int16(19), Int8(5), UInt16(1), category(19), float32(1), int16(7), int32(2), int8(12), uint16(2)
memory usage: 4.2 GB

In [10]:
df.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'MKT_UNIQUE_CARRIER', 'BRANDED_CODE_SHARE', 'MKT_CARRIER_AIRLINE_ID', 'MKT_CARRIER', 'MKT_CARRIER_FL_NUM', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER',
       'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_FIPS', 'ORIGIN_STATE_NM', 'ORIGIN_WAC', 'DEST_AIRPORT_ID',
       'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'DEST_STATE_FIPS', 'DEST_STATE_NM', 'DEST_WAC', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_DELAY_GROUP',
       'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'ARR_DELAY_GROUP', 'ARR_TIME_BLK', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'DUP',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'FLIGHTS', 'DISTANCE', 'DISTANCE_GROUP', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'DIV_AIRPORT_LANDINGS'],
      dtype='object')